local M = {}

-- Ink style objects use the DOM/TypeScript spelling of CSS properties.  Keep
-- this catalog local so completion works without Node, a CSS language server,
-- or a generated cache.
local definitions = {
  { "accentColor", { "auto" } },
  { "alignContent", { "normal", "start", "center", "end", "flex-start", "flex-end", "space-between", "space-around", "space-evenly", "stretch" } },
  { "alignItems", { "normal", "start", "center", "end", "flex-start", "flex-end", "baseline", "stretch" } },
  { "alignSelf", { "auto", "normal", "start", "center", "end", "flex-start", "flex-end", "baseline", "stretch" } },
  { "alignmentBaseline", { "auto", "baseline", "before-edge", "text-before-edge", "middle", "central", "after-edge", "text-after-edge", "ideographic", "alphabetic", "hanging", "mathematical" } },
  { "all", {} },
  { "animation", {} },
  { "animationComposition", { "replace", "add", "accumulate" } },
  { "animationDelay", {} },
  { "animationDirection", { "normal", "reverse", "alternate", "alternate-reverse" } },
  { "animationDuration", {} },
  { "animationFillMode", { "none", "forwards", "backwards", "both" } },
  { "animationIterationCount", { "infinite" } },
  { "animationName", { "none" } },
  { "animationPlayState", { "running", "paused" } },
  { "animationRange", { "normal", "entry", "exit", "cover", "contain" } },
  { "animationRangeEnd", { "normal", "entry", "exit", "cover", "contain" } },
  { "animationRangeStart", { "normal", "entry", "exit", "cover", "contain" } },
  { "animationTimeline", { "auto", "none", "scroll()", "view()" } },
  { "animationTimingFunction", { "linear", "ease", "ease-in", "ease-out", "ease-in-out", "step-start", "step-end", "cubic-bezier()", "steps()" } },
  { "appearance", { "none", "auto", "textfield", "menulist-button" } },
  { "aspectRatio", { "auto" } },
  { "backdropFilter", { "none", "blur()", "brightness()", "contrast()", "drop-shadow()", "grayscale()", "hue-rotate()", "invert()", "opacity()", "saturate()", "sepia()" } },
  { "backfaceVisibility", { "visible", "hidden" } },
  { "background", { "none", "transparent" } },
  { "backgroundAttachment", { "scroll", "fixed", "local" } },
  { "backgroundBlendMode", { "normal", "multiply", "screen", "overlay", "darken", "lighten", "color-dodge", "color-burn", "hard-light", "soft-light", "difference", "exclusion", "hue", "saturation", "color", "luminosity" } },
  { "backgroundClip", { "border-box", "padding-box", "content-box", "text" } },
  { "backgroundColor", { "transparent", "currentColor" } },
  { "backgroundImage", { "none", "url()", "linear-gradient()", "radial-gradient()", "conic-gradient()", "repeating-linear-gradient()", "repeating-radial-gradient()", "repeating-conic-gradient()" } },
  { "backgroundOrigin", { "border-box", "padding-box", "content-box" } },
  { "backgroundPosition", { "left", "center", "right", "top", "bottom" } },
  { "backgroundPositionX", { "left", "center", "right" } },
  { "backgroundPositionY", { "top", "center", "bottom" } },
  { "backgroundRepeat", { "repeat", "repeat-x", "repeat-y", "space", "round", "no-repeat" } },
  { "backgroundSize", { "auto", "cover", "contain" } },
  { "baselineShift", { "baseline", "sub", "super" } },
  { "blockSize", { "auto", "max-content", "min-content", "fit-content", "stretch" } },
  { "border", { "none" } },
  { "borderBlock", { "none" } },
  { "borderBlockColor", { "currentColor", "transparent" } },
  { "borderBlockEnd", { "none" } },
  { "borderBlockEndColor", { "currentColor", "transparent" } },
  { "borderBlockEndStyle", { "none", "hidden", "dotted", "dashed", "solid", "double", "groove", "ridge", "inset", "outset" } },
  { "borderBlockEndWidth", { "thin", "medium", "thick" } },
  { "borderBlockStart", { "none" } },
  { "borderBlockStartColor", { "currentColor", "transparent" } },
  { "borderBlockStartStyle", { "none", "hidden", "dotted", "dashed", "solid", "double", "groove", "ridge", "inset", "outset" } },
  { "borderBlockStartWidth", { "thin", "medium", "thick" } },
  { "borderBlockStyle", { "none", "hidden", "dotted", "dashed", "solid", "double", "groove", "ridge", "inset", "outset" } },
  { "borderBlockWidth", { "thin", "medium", "thick" } },
  { "borderBottom", { "none" } },
  { "borderBottomColor", { "currentColor", "transparent" } },
  { "borderBottomLeftRadius", {} },
  { "borderBottomRightRadius", {} },
  { "borderBottomStyle", { "none", "hidden", "dotted", "dashed", "solid", "double", "groove", "ridge", "inset", "outset" } },
  { "borderBottomWidth", { "thin", "medium", "thick" } },
  { "borderCollapse", { "collapse", "separate" } },
  { "borderColor", { "currentColor", "transparent" } },
  { "borderEndEndRadius", {} },
  { "borderEndStartRadius", {} },
  { "borderImage", { "none" } },
  { "borderImageOutset", {} },
  { "borderImageRepeat", { "stretch", "repeat", "round", "space" } },
  { "borderImageSlice", { "fill" } },
  { "borderImageSource", { "none", "url()", "linear-gradient()", "radial-gradient()" } },
  { "borderImageWidth", { "auto" } },
  { "borderInline", { "none" } },
  { "borderInlineColor", { "currentColor", "transparent" } },
  { "borderInlineEnd", { "none" } },
  { "borderInlineEndColor", { "currentColor", "transparent" } },
  { "borderInlineEndStyle", { "none", "hidden", "dotted", "dashed", "solid", "double", "groove", "ridge", "inset", "outset" } },
  { "borderInlineEndWidth", { "thin", "medium", "thick" } },
  { "borderInlineStart", { "none" } },
  { "borderInlineStartColor", { "currentColor", "transparent" } },
  { "borderInlineStartStyle", { "none", "hidden", "dotted", "dashed", "solid", "double", "groove", "ridge", "inset", "outset" } },
  { "borderInlineStartWidth", { "thin", "medium", "thick" } },
  { "borderInlineStyle", { "none", "hidden", "dotted", "dashed", "solid", "double", "groove", "ridge", "inset", "outset" } },
  { "borderInlineWidth", { "thin", "medium", "thick" } },
  { "borderLeft", { "none" } },
  { "borderLeftColor", { "currentColor", "transparent" } },
  { "borderLeftStyle", { "none", "hidden", "dotted", "dashed", "solid", "double", "groove", "ridge", "inset", "outset" } },
  { "borderLeftWidth", { "thin", "medium", "thick" } },
  { "borderRadius", {} },
  { "borderRight", { "none" } },
  { "borderRightColor", { "currentColor", "transparent" } },
  { "borderRightStyle", { "none", "hidden", "dotted", "dashed", "solid", "double", "groove", "ridge", "inset", "outset" } },
  { "borderRightWidth", { "thin", "medium", "thick" } },
  { "borderSpacing", {} },
  { "borderStartEndRadius", {} },
  { "borderStartStartRadius", {} },
  { "borderStyle", { "none", "hidden", "dotted", "dashed", "solid", "double", "groove", "ridge", "inset", "outset" } },
  { "borderTop", { "none" } },
  { "borderTopColor", { "currentColor", "transparent" } },
  { "borderTopLeftRadius", {} },
  { "borderTopRightRadius", {} },
  { "borderTopStyle", { "none", "hidden", "dotted", "dashed", "solid", "double", "groove", "ridge", "inset", "outset" } },
  { "borderTopWidth", { "thin", "medium", "thick" } },
  { "borderWidth", { "thin", "medium", "thick" } },
  { "bottom", { "auto" } },
  { "boxDecorationBreak", { "slice", "clone" } },
  { "boxShadow", { "none", "inset" } },
  { "boxSizing", { "content-box", "border-box" } },
  { "breakAfter", { "auto", "avoid", "always", "all", "avoid-page", "page", "left", "right", "recto", "verso", "avoid-column", "column", "avoid-region", "region" } },
  { "breakBefore", { "auto", "avoid", "always", "all", "avoid-page", "page", "left", "right", "recto", "verso", "avoid-column", "column", "avoid-region", "region" } },
  { "breakInside", { "auto", "avoid", "avoid-page", "avoid-column", "avoid-region" } },
  { "captionSide", { "top", "bottom", "block-start", "block-end", "inline-start", "inline-end" } },
  { "caretColor", { "auto", "currentColor", "transparent" } },
  { "caretShape", { "auto", "bar", "block", "underscore" } },
  { "clear", { "none", "left", "right", "both", "inline-start", "inline-end" } },
  { "clip", { "auto", "rect()" } },
  { "clipPath", { "none", "url()", "inset()", "circle()", "ellipse()", "polygon()", "path()" } },
  { "clipRule", { "nonzero", "evenodd" } },
  { "color", { "currentColor", "transparent" } },
  { "colorInterpolation", { "auto", "sRGB", "linearRGB" } },
  { "colorScheme", { "normal", "light", "dark", "light dark", "only light" } },
  { "columnCount", { "auto" } },
  { "columnFill", { "auto", "balance", "balance-all" } },
  { "columnGap", { "normal" } },
  { "columnRule", { "none" } },
  { "columnRuleColor", { "currentColor", "transparent" } },
  { "columnRuleStyle", { "none", "hidden", "dotted", "dashed", "solid", "double", "groove", "ridge", "inset", "outset" } },
  { "columnRuleWidth", { "thin", "medium", "thick" } },
  { "columnSpan", { "none", "all" } },
  { "columnWidth", { "auto" } },
  { "columns", { "auto" } },
  { "contain", { "none", "strict", "content", "size", "inline-size", "layout", "style", "paint" } },
  { "containIntrinsicBlockSize", { "none", "auto" } },
  { "containIntrinsicHeight", { "none", "auto" } },
  { "containIntrinsicInlineSize", { "none", "auto" } },
  { "containIntrinsicSize", { "none", "auto" } },
  { "containIntrinsicWidth", { "none", "auto" } },
  { "container", { "none", "normal" } },
  { "containerName", { "none" } },
  { "containerType", { "normal", "size", "inline-size" } },
  { "content", { "normal", "none", "open-quote", "close-quote", "no-open-quote", "no-close-quote", "attr()", "counter()", "counters()", "url()" } },
  { "contentVisibility", { "visible", "auto", "hidden" } },
  { "counterIncrement", { "none" } },
  { "counterReset", { "none" } },
  { "counterSet", { "none" } },
  { "cursor", { "auto", "default", "none", "context-menu", "help", "pointer", "progress", "wait", "cell", "crosshair", "text", "vertical-text", "alias", "copy", "move", "no-drop", "not-allowed", "grab", "grabbing", "all-scroll", "col-resize", "row-resize", "n-resize", "e-resize", "s-resize", "w-resize", "ne-resize", "nw-resize", "se-resize", "sw-resize", "ew-resize", "ns-resize", "nesw-resize", "nwse-resize", "zoom-in", "zoom-out" } },
  { "direction", { "ltr", "rtl" } },
  { "display", { "none", "contents", "block", "inline", "inline-block", "flow-root", "list-item", "flex", "inline-flex", "grid", "inline-grid", "table", "inline-table", "table-row", "table-cell" } },
  { "dominantBaseline", { "auto", "text-bottom", "alphabetic", "ideographic", "middle", "central", "mathematical", "hanging", "text-top" } },
  { "emptyCells", { "show", "hide" } },
  { "fill", { "none", "currentColor", "context-fill", "context-stroke" } },
  { "fillOpacity", {} },
  { "fillRule", { "nonzero", "evenodd" } },
  { "filter", { "none", "url()", "blur()", "brightness()", "contrast()", "drop-shadow()", "grayscale()", "hue-rotate()", "invert()", "opacity()", "saturate()", "sepia()" } },
  { "flex", { "none", "auto", "initial" } },
  { "flexBasis", { "auto", "content", "max-content", "min-content", "fit-content" } },
  { "flexDirection", { "row", "row-reverse", "column", "column-reverse" } },
  { "flexFlow", { "row", "row-reverse", "column", "column-reverse", "nowrap", "wrap", "wrap-reverse" } },
  { "flexGrow", {} },
  { "flexShrink", {} },
  { "flexWrap", { "nowrap", "wrap", "wrap-reverse" } },
  { "float", { "none", "left", "right", "inline-start", "inline-end" } },
  { "floodColor", { "currentColor", "transparent" } },
  { "floodOpacity", {} },
  { "font", {} },
  { "fontFamily", { "serif", "sans-serif", "monospace", "cursive", "fantasy", "system-ui", "ui-serif", "ui-sans-serif", "ui-monospace", "ui-rounded", "emoji", "math", "fangsong" } },
  { "fontFeatureSettings", { "normal" } },
  { "fontKerning", { "auto", "normal", "none" } },
  { "fontOpticalSizing", { "auto", "none" } },
  { "fontPalette", { "normal", "light", "dark" } },
  { "fontSize", { "xx-small", "x-small", "small", "medium", "large", "x-large", "xx-large", "xxx-large", "smaller", "larger" } },
  { "fontSizeAdjust", { "none", "from-font" } },
  { "fontStretch", { "normal", "ultra-condensed", "extra-condensed", "condensed", "semi-condensed", "semi-expanded", "expanded", "extra-expanded", "ultra-expanded" } },
  { "fontStyle", { "normal", "italic", "oblique" } },
  { "fontSynthesis", { "none", "weight", "style", "small-caps", "position" } },
  { "fontVariant", { "normal", "none", "small-caps" } },
  { "fontVariantCaps", { "normal", "small-caps", "all-small-caps", "petite-caps", "all-petite-caps", "unicase", "titling-caps" } },
  { "fontVariantEastAsian", { "normal", "ruby", "jis78", "jis83", "jis90", "jis04", "simplified", "traditional", "full-width", "proportional-width" } },
  { "fontVariantLigatures", { "normal", "none", "common-ligatures", "no-common-ligatures", "discretionary-ligatures", "no-discretionary-ligatures", "historical-ligatures", "no-historical-ligatures", "contextual", "no-contextual" } },
  { "fontVariantNumeric", { "normal", "ordinal", "slashed-zero", "lining-nums", "oldstyle-nums", "proportional-nums", "tabular-nums", "diagonal-fractions", "stacked-fractions" } },
  { "fontVariationSettings", { "normal" } },
  { "fontWeight", { "normal", "bold", "bolder", "lighter" } },
  { "gap", { "normal" } },
  { "grid", { "none" } },
  { "gridArea", { "auto" } },
  { "gridAutoColumns", { "auto", "max-content", "min-content", "minmax()", "fit-content()" } },
  { "gridAutoFlow", { "row", "column", "dense", "row dense", "column dense" } },
  { "gridAutoRows", { "auto", "max-content", "min-content", "minmax()", "fit-content()" } },
  { "gridColumn", { "auto" } },
  { "gridColumnEnd", { "auto", "span" } },
  { "gridColumnGap", { "normal" } },
  { "gridColumnStart", { "auto", "span" } },
  { "gridGap", { "normal" } },
  { "gridRow", { "auto" } },
  { "gridRowEnd", { "auto", "span" } },
  { "gridRowGap", { "normal" } },
  { "gridRowStart", { "auto", "span" } },
  { "gridTemplate", { "none" } },
  { "gridTemplateAreas", { "none" } },
  { "gridTemplateColumns", { "none", "subgrid", "masonry", "repeat()", "minmax()", "fit-content()" } },
  { "gridTemplateRows", { "none", "subgrid", "masonry", "repeat()", "minmax()", "fit-content()" } },
  { "height", { "auto", "max-content", "min-content", "fit-content", "stretch" } },
  { "hyphenateCharacter", { "auto" } },
  { "hyphens", { "none", "manual", "auto" } },
  { "imageRendering", { "auto", "smooth", "high-quality", "crisp-edges", "pixelated" } },
  { "inlineSize", { "auto", "max-content", "min-content", "fit-content", "stretch" } },
  { "inset", { "auto" } },
  { "insetBlock", { "auto" } },
  { "insetBlockEnd", { "auto" } },
  { "insetBlockStart", { "auto" } },
  { "insetInline", { "auto" } },
  { "insetInlineEnd", { "auto" } },
  { "insetInlineStart", { "auto" } },
  { "isolation", { "auto", "isolate" } },
  { "justifyContent", { "normal", "start", "center", "end", "flex-start", "flex-end", "left", "right", "space-between", "space-around", "space-evenly", "stretch" } },
  { "justifyItems", { "normal", "stretch", "center", "start", "end", "self-start", "self-end", "left", "right", "legacy" } },
  { "justifySelf", { "auto", "normal", "stretch", "center", "start", "end", "self-start", "self-end", "left", "right" } },
  { "left", { "auto" } },
  { "letterSpacing", { "normal" } },
  { "lightingColor", { "currentColor" } },
  { "lineBreak", { "auto", "loose", "normal", "strict", "anywhere" } },
  { "lineClamp", { "none" } },
  { "lineHeight", { "normal" } },
  { "listStyle", { "none" } },
  { "listStyleImage", { "none", "url()", "linear-gradient()" } },
  { "listStylePosition", { "inside", "outside" } },
  { "listStyleType", { "none", "disc", "circle", "square", "decimal", "decimal-leading-zero", "lower-roman", "upper-roman", "lower-alpha", "upper-alpha" } },
  { "margin", { "auto" } },
  { "marginBlock", { "auto" } },
  { "marginBlockEnd", { "auto" } },
  { "marginBlockStart", { "auto" } },
  { "marginBottom", { "auto" } },
  { "marginInline", { "auto" } },
  { "marginInlineEnd", { "auto" } },
  { "marginInlineStart", { "auto" } },
  { "marginLeft", { "auto" } },
  { "marginRight", { "auto" } },
  { "marginTop", { "auto" } },
  { "marker", { "none", "url()" } },
  { "markerEnd", { "none", "url()" } },
  { "markerMid", { "none", "url()" } },
  { "markerStart", { "none", "url()" } },
  { "mask", { "none" } },
  { "maskClip", { "border-box", "padding-box", "content-box", "fill-box", "stroke-box", "view-box", "no-clip" } },
  { "maskComposite", { "add", "subtract", "intersect", "exclude" } },
  { "maskImage", { "none", "url()", "linear-gradient()", "radial-gradient()" } },
  { "maskMode", { "match-source", "alpha", "luminance" } },
  { "maskOrigin", { "border-box", "padding-box", "content-box", "fill-box", "stroke-box", "view-box" } },
  { "maskPosition", { "left", "center", "right", "top", "bottom" } },
  { "maskRepeat", { "repeat", "repeat-x", "repeat-y", "space", "round", "no-repeat" } },
  { "maskSize", { "auto", "cover", "contain" } },
  { "maskType", { "luminance", "alpha" } },
  { "maxBlockSize", { "none", "max-content", "min-content", "fit-content", "stretch" } },
  { "maxHeight", { "none", "max-content", "min-content", "fit-content", "stretch" } },
  { "maxInlineSize", { "none", "max-content", "min-content", "fit-content", "stretch" } },
  { "maxWidth", { "none", "max-content", "min-content", "fit-content", "stretch" } },
  { "minBlockSize", { "auto", "max-content", "min-content", "fit-content", "stretch" } },
  { "minHeight", { "auto", "max-content", "min-content", "fit-content", "stretch" } },
  { "minInlineSize", { "auto", "max-content", "min-content", "fit-content", "stretch" } },
  { "minWidth", { "auto", "max-content", "min-content", "fit-content", "stretch" } },
  { "mixBlendMode", { "normal", "multiply", "screen", "overlay", "darken", "lighten", "color-dodge", "color-burn", "hard-light", "soft-light", "difference", "exclusion", "hue", "saturation", "color", "luminosity", "plus-darker", "plus-lighter" } },
  { "objectFit", { "fill", "contain", "cover", "none", "scale-down" } },
  { "objectPosition", { "left", "center", "right", "top", "bottom" } },
  { "offset", { "none" } },
  { "offsetAnchor", { "auto" } },
  { "offsetDistance", {} },
  { "offsetPath", { "none", "ray()", "url()", "path()" } },
  { "offsetPosition", { "normal", "auto" } },
  { "offsetRotate", { "auto", "reverse" } },
  { "opacity", {} },
  { "order", {} },
  { "orphans", {} },
  { "outline", { "none" } },
  { "outlineColor", { "auto", "currentColor", "transparent" } },
  { "outlineOffset", {} },
  { "outlineStyle", { "auto", "none", "dotted", "dashed", "solid", "double", "groove", "ridge", "inset", "outset" } },
  { "outlineWidth", { "thin", "medium", "thick" } },
  { "overflow", { "visible", "hidden", "clip", "scroll", "auto" } },
  { "overflowAnchor", { "auto", "none" } },
  { "overflowBlock", { "visible", "hidden", "clip", "scroll", "auto" } },
  { "overflowClipMargin", { "content-box", "padding-box", "border-box" } },
  { "overflowInline", { "visible", "hidden", "clip", "scroll", "auto" } },
  { "overflowWrap", { "normal", "break-word", "anywhere" } },
  { "overflowX", { "visible", "hidden", "clip", "scroll", "auto" } },
  { "overflowY", { "visible", "hidden", "clip", "scroll", "auto" } },
  { "overscrollBehavior", { "auto", "contain", "none" } },
  { "overscrollBehaviorBlock", { "auto", "contain", "none" } },
  { "overscrollBehaviorInline", { "auto", "contain", "none" } },
  { "overscrollBehaviorX", { "auto", "contain", "none" } },
  { "overscrollBehaviorY", { "auto", "contain", "none" } },
  { "padding", {} },
  { "paddingBlock", {} },
  { "paddingBlockEnd", {} },
  { "paddingBlockStart", {} },
  { "paddingBottom", {} },
  { "paddingInline", {} },
  { "paddingInlineEnd", {} },
  { "paddingInlineStart", {} },
  { "paddingLeft", {} },
  { "paddingRight", {} },
  { "paddingTop", {} },
  { "pageBreakAfter", { "auto", "always", "avoid", "left", "right", "recto", "verso" } },
  { "pageBreakBefore", { "auto", "always", "avoid", "left", "right", "recto", "verso" } },
  { "pageBreakInside", { "auto", "avoid" } },
  { "paintOrder", { "normal", "fill", "stroke", "markers" } },
  { "perspective", { "none" } },
  { "perspectiveOrigin", { "left", "center", "right", "top", "bottom" } },
  { "placeContent", { "normal", "start", "center", "end", "flex-start", "flex-end", "space-between", "space-around", "space-evenly", "stretch" } },
  { "placeItems", { "normal", "start", "center", "end", "flex-start", "flex-end", "baseline", "stretch" } },
  { "placeSelf", { "auto", "normal", "start", "center", "end", "flex-start", "flex-end", "baseline", "stretch" } },
  { "pointerEvents", { "auto", "none", "visiblePainted", "visibleFill", "visibleStroke", "visible", "painted", "fill", "stroke", "all" } },
  { "position", { "static", "relative", "absolute", "fixed", "sticky" } },
  { "quotes", { "auto", "none" } },
  { "resize", { "none", "both", "horizontal", "vertical", "block", "inline" } },
  { "right", { "auto" } },
  { "rotate", { "none" } },
  { "rowGap", { "normal" } },
  { "rubyAlign", { "start", "center", "space-between", "space-around" } },
  { "rubyPosition", { "over", "under", "inter-character", "alternate" } },
  { "scale", { "none" } },
  { "scrollBehavior", { "auto", "smooth" } },
  { "scrollMargin", {} },
  { "scrollMarginBlock", {} },
  { "scrollMarginBlockEnd", {} },
  { "scrollMarginBlockStart", {} },
  { "scrollMarginBottom", {} },
  { "scrollMarginInline", {} },
  { "scrollMarginInlineEnd", {} },
  { "scrollMarginInlineStart", {} },
  { "scrollMarginLeft", {} },
  { "scrollMarginRight", {} },
  { "scrollMarginTop", {} },
  { "scrollPadding", { "auto" } },
  { "scrollPaddingBlock", { "auto" } },
  { "scrollPaddingBlockEnd", { "auto" } },
  { "scrollPaddingBlockStart", { "auto" } },
  { "scrollPaddingBottom", { "auto" } },
  { "scrollPaddingInline", { "auto" } },
  { "scrollPaddingInlineEnd", { "auto" } },
  { "scrollPaddingInlineStart", { "auto" } },
  { "scrollPaddingLeft", { "auto" } },
  { "scrollPaddingRight", { "auto" } },
  { "scrollPaddingTop", { "auto" } },
  { "scrollSnapAlign", { "none", "start", "end", "center" } },
  { "scrollSnapStop", { "normal", "always" } },
  { "scrollSnapType", { "none", "x", "y", "block", "inline", "both", "mandatory", "proximity" } },
  { "scrollbarColor", { "auto" } },
  { "scrollbarGutter", { "auto", "stable", "both-edges" } },
  { "scrollbarWidth", { "auto", "thin", "none" } },
  { "shapeImageThreshold", {} },
  { "shapeMargin", {} },
  { "shapeOutside", { "none", "margin-box", "border-box", "padding-box", "content-box", "inset()", "circle()", "ellipse()", "polygon()", "url()" } },
  { "stopColor", { "currentColor", "transparent" } },
  { "stopOpacity", {} },
  { "stroke", { "none", "currentColor", "context-fill", "context-stroke" } },
  { "strokeDasharray", { "none" } },
  { "strokeDashoffset", {} },
  { "strokeLinecap", { "butt", "round", "square" } },
  { "strokeLinejoin", { "miter", "miter-clip", "round", "bevel", "arcs" } },
  { "strokeMiterlimit", {} },
  { "strokeOpacity", {} },
  { "strokeWidth", {} },
  { "tabSize", {} },
  { "tableLayout", { "auto", "fixed" } },
  { "textAlign", { "start", "end", "left", "right", "center", "justify", "match-parent" } },
  { "textAlignLast", { "auto", "start", "end", "left", "right", "center", "justify" } },
  { "textAnchor", { "start", "middle", "end" } },
  { "textCombineUpright", { "none", "all" } },
  { "textDecoration", { "none", "underline", "overline", "line-through", "blink", "solid", "double", "dotted", "dashed", "wavy" } },
  { "textDecorationColor", { "currentColor", "transparent" } },
  { "textDecorationLine", { "none", "underline", "overline", "line-through", "blink" } },
  { "textDecorationSkipInk", { "auto", "none", "all" } },
  { "textDecorationStyle", { "solid", "double", "dotted", "dashed", "wavy" } },
  { "textDecorationThickness", { "auto", "from-font" } },
  { "textEmphasis", { "none" } },
  { "textEmphasisColor", { "currentColor", "transparent" } },
  { "textEmphasisPosition", { "over", "under", "right", "left" } },
  { "textEmphasisStyle", { "none", "filled", "open", "dot", "circle", "double-circle", "triangle", "sesame" } },
  { "textIndent", { "hanging", "each-line" } },
  { "textJustify", { "auto", "none", "inter-word", "inter-character" } },
  { "textOrientation", { "mixed", "upright", "sideways" } },
  { "textOverflow", { "clip", "ellipsis" } },
  { "textRendering", { "auto", "optimizeSpeed", "optimizeLegibility", "geometricPrecision" } },
  { "textShadow", { "none" } },
  { "textTransform", { "none", "capitalize", "uppercase", "lowercase", "full-width", "full-size-kana", "math-auto" } },
  { "textUnderlineOffset", { "auto" } },
  { "textUnderlinePosition", { "auto", "from-font", "under", "left", "right" } },
  { "textWrap", { "wrap", "nowrap", "balance", "pretty", "stable" } },
  { "textWrapMode", { "wrap", "nowrap" } },
  { "textWrapStyle", { "auto", "balance", "stable", "pretty" } },
  { "top", { "auto" } },
  { "touchAction", { "auto", "none", "pan-x", "pan-left", "pan-right", "pan-y", "pan-up", "pan-down", "pinch-zoom", "manipulation" } },
  { "transform", { "none", "matrix()", "matrix3d()", "perspective()", "rotate()", "rotate3d()", "rotateX()", "rotateY()", "rotateZ()", "scale()", "scale3d()", "scaleX()", "scaleY()", "scaleZ()", "skew()", "skewX()", "skewY()", "translate()", "translate3d()", "translateX()", "translateY()", "translateZ()" } },
  { "transformBox", { "content-box", "border-box", "fill-box", "stroke-box", "view-box" } },
  { "transformOrigin", { "left", "center", "right", "top", "bottom" } },
  { "transformStyle", { "flat", "preserve-3d" } },
  { "transition", { "none" } },
  { "transitionBehavior", { "normal", "allow-discrete" } },
  { "transitionDelay", {} },
  { "transitionDuration", {} },
  { "transitionProperty", { "none", "all" } },
  { "transitionTimingFunction", { "linear", "ease", "ease-in", "ease-out", "ease-in-out", "step-start", "step-end", "cubic-bezier()", "steps()" } },
  { "translate", { "none" } },
  { "unicodeBidi", { "normal", "embed", "isolate", "bidi-override", "isolate-override", "plaintext" } },
  { "userSelect", { "auto", "text", "none", "contain", "all" } },
  { "vectorEffect", { "none", "non-scaling-stroke", "non-scaling-size", "non-rotation", "fixed-position" } },
  { "verticalAlign", { "baseline", "sub", "super", "text-top", "text-bottom", "middle", "top", "bottom" } },
  { "visibility", { "visible", "hidden", "collapse" } },
  { "whiteSpace", { "normal", "pre", "nowrap", "pre-wrap", "pre-line", "break-spaces", "collapse", "preserve", "preserve-breaks", "preserve-spaces", "break-spaces", "wrap" } },
  { "whiteSpaceCollapse", { "collapse", "preserve", "preserve-breaks", "preserve-spaces", "break-spaces" } },
  { "widows", {} },
  { "width", { "auto", "max-content", "min-content", "fit-content", "stretch" } },
  { "willChange", { "auto", "scroll-position", "contents" } },
  { "wordBreak", { "normal", "break-all", "keep-all", "break-word", "auto-phrase" } },
  { "wordSpacing", { "normal" } },
  { "wordWrap", { "normal", "break-word", "anywhere" } },
  { "writingMode", { "horizontal-tb", "vertical-rl", "vertical-lr", "sideways-rl", "sideways-lr" } },
  { "zIndex", { "auto" } },
  { "zoom", { "normal", "reset" } },
}

-- Remaining standard/SVG keys from csstype 3.2.3's `Properties` surface.
-- They intentionally have no small keyword list yet, but still participate in
-- property completion. Vendor-prefixed and obsolete interfaces are omitted.
local derived_properties = {
  "alignTracks",
  "anchorName",
  "anchorScope",
  "caret",
  "colorAdjust",
  "colorInterpolationFilters",
  "colorRendering",
  "cx",
  "cy",
  "d",
  "fieldSizing",
  "fontLanguageOverride",
  "fontSmooth",
  "fontSynthesisPosition",
  "fontSynthesisSmallCaps",
  "fontSynthesisStyle",
  "fontSynthesisWeight",
  "fontVariantAlternates",
  "fontVariantEmoji",
  "fontVariantPosition",
  "fontWidth",
  "forcedColorAdjust",
  "glyphOrientationVertical",
  "hangingPunctuation",
  "hyphenateLimitChars",
  "imageOrientation",
  "imageResolution",
  "initialLetter",
  "initialLetterAlign",
  "interpolateSize",
  "justifyTracks",
  "lineHeightStep",
  "marginTrim",
  "maskBorder",
  "maskBorderMode",
  "maskBorderOutset",
  "maskBorderRepeat",
  "maskBorderSlice",
  "maskBorderSource",
  "maskBorderWidth",
  "masonryAutoFlow",
  "mathDepth",
  "mathShift",
  "mathStyle",
  "maxLines",
  "motion",
  "motionDistance",
  "motionPath",
  "motionRotation",
  "objectViewBox",
  "offsetRotation",
  "overflowClipBox",
  "overlay",
  "page",
  "positionAnchor",
  "positionArea",
  "positionTry",
  "positionTryFallbacks",
  "positionTryOrder",
  "positionVisibility",
  "printColorAdjust",
  "r",
  "rubyMerge",
  "rubyOverhang",
  "rx",
  "ry",
  "scrollInitialTarget",
  "scrollSnapMargin",
  "scrollSnapMarginBottom",
  "scrollSnapMarginLeft",
  "scrollSnapMarginRight",
  "scrollSnapMarginTop",
  "scrollTimeline",
  "scrollTimelineAxis",
  "scrollTimelineName",
  "shapeRendering",
  "speakAs",
  "strokeColor",
  "textAutospace",
  "textBox",
  "textBoxEdge",
  "textBoxTrim",
  "textDecorationSkip",
  "textSizeAdjust",
  "textSpacingTrim",
  "timelineScope",
  "viewTimeline",
  "viewTimelineAxis",
  "viewTimelineInset",
  "viewTimelineName",
  "viewTransitionClass",
  "viewTransitionName",
  "x",
  "y",
}

local css_wide_values = { "inherit", "initial", "revert", "revert-layer", "unset" }
local generic_values = {
  "var()",
  "calc()",
  "min()",
  "max()",
  "clamp()",
  "env()",
  "=expression",
}

local property_names = {}
local property_values = {}
local property_set = {}

for _, definition in ipairs(definitions) do
  local name = definition[1]
  property_names[#property_names + 1] = name
  property_values[name] = definition[2]
  property_set[name] = true
end

for _, name in ipairs(derived_properties) do
  if not property_set[name] then
    property_names[#property_names + 1] = name
    property_values[name] = {}
    property_set[name] = true
  end
end

table.sort(property_names)

local function copy(list)
  local result = {}
  for i, value in ipairs(list) do
    result[i] = value
  end
  return result
end

local function starts_with(value, prefix)
  if prefix == nil or prefix == "" then
    return true
  end
  return value:sub(1, #prefix):lower() == prefix:lower()
end

local function append_unique(target, seen, values)
  for _, value in ipairs(values) do
    if not seen[value] then
      seen[value] = true
      target[#target + 1] = value
    end
  end
end

---Return all supported camelCase CSS property names in stable order.
---@return string[]
function M.property_names()
  return copy(property_names)
end

---Return whether `name` is a catalogued CSS property.
---@param name string?
---@return boolean
function M.is_property(name)
  return name ~= nil and property_set[name] == true
end

---Return CSS values that are useful for `property`.
---Property-specific values come first, followed by CSS-wide and expression
---forms. The returned table is a copy and may be changed by the caller.
---@param property string?
---@return string[]
function M.values_for(property)
  local result, seen = {}, {}
  if property and property_values[property] then
    append_unique(result, seen, property_values[property])
  end
  append_unique(result, seen, css_wide_values)
  append_unique(result, seen, generic_values)
  return result
end

---Filter property names by a case-insensitive prefix.
---@param prefix string?
---@return string[]
function M.complete_properties(prefix)
  local result = {}
  for _, name in ipairs(property_names) do
    if starts_with(name, prefix) then
      result[#result + 1] = name
    end
  end
  return result
end

---Filter values for a property by a case-insensitive prefix.
---@param property string?
---@param prefix string?
---@return string[]
function M.complete_values(property, prefix)
  local result = {}
  for _, value in ipairs(M.values_for(property)) do
    if starts_with(value, prefix) then
      result[#result + 1] = value
    end
  end
  return result
end

-- Public read-only-by-convention data is useful to completion adapters and
-- tests, while the helper functions above avoid sharing mutable result lists.
M.properties = property_names
M.property_values = property_values
M.css_wide_values = css_wide_values
M.generic_values = generic_values

return M
